[package]
name = "bridge-contracts"
version = "0.4.0"
authors = ["debris <marek.kotewicz@gmail.com>", "snd <kruemaxi@gmail.com>"]

[dependencies]
ethabi = "5.1"
ethabi-derive = "5.0"
ethabi-contract = "5.0"
